# Generated by Django 4.1.3 on 2023-12-04 18:24

from django.db import migrations, models
import userapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=userapi.models.upload_to),
        ),
    ]
