# Generated by Django 4.1.3 on 2022-11-03 08:58

from django.db import migrations, models
import django.db.models.deletion
import yamod.models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0003_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('length', models.PositiveIntegerField(verbose_name=yamod.models.Season)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yamod.season')),
            ],
        ),
    ]
