# Generated by Django 4.1.3 on 2022-11-10 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0005_alter_season_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.PositiveIntegerField(help_text='in EUR')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yamod.movie')),
            ],
        ),
    ]
