# Generated by Django 4.1.3 on 2022-11-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0002_tvshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_no', models.IntegerField()),
                ('cast', models.ManyToManyField(to='yamod.person')),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yamod.tvshow')),
            ],
        ),
    ]
