# Generated by Django 4.2.6 on 2023-10-24 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=1024)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True)),
                ('genre', models.ManyToManyField(to='yamod.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_title', models.CharField(max_length=1024)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True)),
                ('order', models.IntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yamod.series')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_title', models.CharField(max_length=1024)),
                ('runtime', models.IntegerField(default=90, help_text='in minutes')),
                ('released', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yamod.season')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='role',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yamod.series'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('person', 'movie', 'series', 'role')},
        ),
    ]
