# Generated by Django 4.2.6 on 2023-10-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0002_series_season_episode_alter_role_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
