# Generated by Django 4.2.6 on 2023-10-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0003_alter_series_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
