# Generated by Django 4.1.3 on 2023-12-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0006_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='black_and_white',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='length',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
